### ISSUE TITLE
Ability to do cached/smarter builds

### ISSUE THREAD

**Issue by nikophil** [symfony-tools/docs-builder#10]
see https://github.com/weaverryan/symfony-docs/issues/18

**Comment by nikophil** [comment]
discussion opened on the parser repo:
https://github.com/doctrine/rst-parser/issues/85

**Comment by weaverryan** [comment]
This is now merged upstream :)

**Comment by weaverryan** [comment]
Oh, actually, small thing, we need a flag to be able to build but ignore the cache. There is already a method on Configuration to control this

**Comment by javiereguiluz** [comment]
Closing as fixed because we have this method to disable the cache: https://github.com/symfony-tools/docs-builder/blob/f34eaabf76580e54397ac1bf5b1fa2c3053d6a77/src/BuildConfig.php#L91
