### ISSUE TITLE
Add support for the "contents" directive

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-tools/docs-builder#113]
While generating Symfony Docs I found this error:

```
Unknown directive: "contents" in "testing" for line ".. contents::"
```

It's because in this file --> https://raw.githubusercontent.com/symfony/symfony-docs/4.4/testing.rst

we have things like this:

```rst
.. contents::
    :local:
    :depth: 1
```

I didn't know this directive. Apparently, it's used to add TOCs in the middle of some doc with the headings of the sections below this directive (http://docutils.sourceforge.net/docs/ref/rst/directives.html#table-of-contents).

So, should we add support for this directive (which is used very rarely in our docs) or should we reword our docs to remove it? Thanks.

**Comment by wouterj** [comment]
I think it's worth adding support for this directive (I introduced it in the docs :smile: ), as I quite like this sub-TOCs (especially since we limit the main TOC to 2 levels, which makes a lot of sense).

**Comment by jdreesen** [comment]
Sounds like a great idea for e.g. this page: https://symfony.com/doc/current/reference/configuration/framework.html

**Comment by javiereguiluz** [comment]
Let's close this issue. It's been more than 2 years since it was created. We didn't receive any feedback, nobody tried to implement this and, more importantly, we never needed it in Symfony Docs. I think it's better to focus our resources on other things that provide more value. Thanks!
