### ISSUE TITLE
Provide a context object with the full app information

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-tools/docs-builder#117]
When parsing a specific book I need to add `Step 0`, `Step 1`, etc. to `<h1>` headings of each article and also, inside each article, I need to number `<h2>` headings as `0.0', `0.1', `0.2`, ..., `1.0`, `1.1`, `1.2`, etc.

I created a TitleNodeRenderer but I can't get the name of the file being parsed, which is the one that contains both the book name and the chapter number. I wish we had a context object with all the essential parsing information available everywhere to unlock powerful features.

Thanks!

**Comment by wouterj** [comment]
Note that Sphinx solves section numbers using a transformer/node visitor. Something I wish to implement after finishing my security doc rewrite (https://github.com/doctrine/rst-parser/issues/145)

**Comment by javiereguiluz** [comment]
Let's close this one. I never needed this again since I first reported this. Let's be flexible and adapt to how things are. Thanks!
