### ISSUE TITLE
[symfony-cloud] broken links

### ISSUE THREAD

**Issue by jrushlow** [symfony-tools/docs-builder#130]
Just ran across this while working on a different project - issue does not cover something specific to `docs-builder` but is more or less a reminder to dig into this a bit more as time allows.

aside links break from secondary pages

![cookbooks](https://user-images.githubusercontent.com/40327885/139240951-321265b4-9370-4892-8189-9e44a6babd58.gif)

**Comment by javiereguiluz** [comment]
We've deployed some changes to symofny.com so I'm closing this as fixed.

I was wrong and the problem was not about the RST parser but about how we render the sidebar menu on symfony.com. Cheers!
