### ISSUE TITLE
Issues with some includes when using Windows

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-tools/docs-builder#144]
Originally reported by @karaka200  and @almaz-free in https://github.com/symfony/symfony-docs/issues/16449:

- - - - -

For build documentation locally, after executing `php build.php` command, the following error is displayed:

```
In FileIncluder.php line 47:

  Include ".. include:: /components/require_autoload.rst.inc" does not exist or is not readable.
```

- - - - -

same error on windows 10 with php-8.1.2-Win32-vs16-x64.zip
(on linux no error)
In file FileIncluder.php on line 44 variable $path conatin:
"C:\projects\symfony-docs-6.0/components/components/require_autoload.rst.inc"
but real path is
"C:\projects\symfony-docs-6.0\components\require_autoload.rst.inc"

- - - - -

It works on macOS too, so I guess this is only an issue on Windows. Let's see if someone can try to debug and fix this. Thanks!

**Comment by javiereguiluz** [comment]
Closing because we didn't receive any other feedback about this issue or any other similar reports. It could be a temporary issue. Thanks.

**Comment by jmsche** [comment]
Hi, can we please reopen this issue?

I'm getting quite the same error (but truncated):

```
php build.php

 Building all Symfony Docs...

 // cache: enabled / output file type(s): HTML

 // Tip: add the --disable-cache option to this command to force the re-build of all docs.


In FileIncluder.php line 47:

" does not exist or is not readable.  ms/types/options/choice_translation_domain.rst.inc
```

This file definitely exists and does not seem to have any permission issues.

Tried removing the entire Git repository and installing it again, without luck.

Note: this happens on my WSL2 Debian 11.6 virtual machine (with PHP 8.2.4 & PHP 8.1.17), but works fine on Linux Mint.

**Comment by yanbog** [comment]
I'm getting quite the same error.
```
Building all Symfony Docs...

 // cache: enabled / output file type(s): HTML

 // Tip: add the --disable-cache option to this command to force the re-build of all docs.


In FileIncluder.php line 47:

  Include ".. include:: /components/require_autoload.rst.inc" does not exist or is not readable.


build-docs [--generate-fjson-files] [--disable-cache]

```
Note: this happens on my Windows 11 23H2 with PHP8.1.26
