### ISSUE TITLE
Bad anchor in MethodReference

### ISSUE THREAD

**Issue by alamirault** [symfony-tools/docs-builder#159]
:method:`Symfony\\Component\\OptionsResolver\\OptionsResolver::setDeprecated`

render the follwing link https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/OptionsResolver/OptionsResolver.php#method_setDeprecated

It seems anchor doesn't exist on github.

https://github.com/symfony-tools/docs-builder/blob/11d9d81e3997e771ad1a57eabaa51fc22c500b35/src/Reference/MethodReference.php#L45

I saw URL was `https://api.symfony.com` in past, maybe it was only supported here ? And we have to remove this part ?

Click and go to the good line directly it's a better experience, but I don't know if Github support it (except with L123)

**Comment by wouterj** [comment]
Yes, we can't link to a method on github and the anchor is a relic from the old api.symfony.com website.

We asked GitHub about this a couple years ago and they weren't immediately against adding these "named anchors", but given the new web-ide features added to GitHub recently I don't think this will ever be supported anymore.

**Comment by alamirault** [comment]
`Scroll-To-Text Fragment` works on Chrome, Edge and Safari (but not on firefox :disappointed:)

https://caniuse.com/url-scroll-to-text-fragment

Example:
`https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/OptionsResolver/OptionsResolver.php#:~:text=function%20setDeprecated`

Maybe we can use it ? Anchor doesn't work today so it cannot be worst
