### ISSUE TITLE
Build is failing due to deprecations

### ISSUE THREAD

**Issue by OskarStark** [symfony-tools/docs-builder#163]
![CleanShot 2023-10-06 at 08 35 21@2x](https://github.com/symfony-tools/docs-builder/assets/995707/1ade9e5b-ac1b-40d3-9112-bd8e123968bd)

**Comment by javiereguiluz** [comment]
Those deprecations come from Doctrine's RST parser ... so we can't do anything for now.

**Comment by smnandre** [comment]
I suggested a fix https://github.com/doctrine/rst-parser/issues/274

**Comment by smnandre** [comment]
This is [fixed](https://github.com/doctrine/rst-parser/pull/278) 🎩   (will be available in next 0.5.6 release)
