### ISSUE TITLE
Sth like this could be spotted by the docs-builder

### ISSUE THREAD

**Issue by OskarStark** [symfony-tools/docs-builder#23]
https://github.com/symfony/symfony-docs/pull/11032

https://github.com/symfony/symfony-docs/pull/11030

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix" because I don't see any way in this could be automated. Many times, the references refer to old headlines which we reworded. So, we can't remove them because that'd break the links with anchors.

Thanks.
