### ISSUE TITLE
CI Check - Code sniffer

### ISSUE THREAD

**Issue by nikophil** [symfony-tools/docs-builder#7]
see https://github.com/weaverryan/symfony-docs/issues/16

**Comment by javiereguiluz** [comment]
Let's close this one as fixed. We already have a "code blocks checker" that checks the source code validity. See https://github.com/symfony/symfony-docs/blob/61d8041981f96a7aea910db3b335b1c8d62aaf5e/.github/workflows/ci.yaml#L80 Thanks!
