### ISSUE TITLE
Minor issue with nested lists

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-tools/docs-builder#70]
In this file -> https://github.com/EasyCorp/EasyAdminBundle/blob/master/doc/events.rst we have this:

```rst
All events are triggered using objects instead of event names defined as strings
(as recommended since Symfony 4.3). They are defined under the
``EasyCorp\Bundle\EasyAdminBundle\Event\`` namespace:

* Events related to Doctrine entities:

  * ``AfterEntityBuiltEvent``
  * ``AfterEntityDeletedEvent``
  * ``AfterEntityPersistedEvent``
  * ``AfterEntityUpdatedEvent``
  * ``BeforeEntityDeletedEvent``
  * ``BeforeEntityPersistedEvent``
  * ``BeforeEntityUpdatedEvent``

* Events related to resource admins:

  * ``AfterCrudActionEvent``
  * ``BeforeCrudActionEvent``
```

This is the right way to create nested lists for Sphinx (so I guess it's the right way in RST in general too). That includes the blank lines after the first level bullets. In the current parser it works OK, but in the new parser it generates this wrong HTML:

![image](https://user-images.githubusercontent.com/73419/110940033-91a64e00-8336-11eb-93c8-dc35e5ce9a1c.png)

As you can see, the nested `<ul>` is outside of the `<li>`, but it should be inside of it.

**Comment by fabpot** [comment]
I can confirm the issue.

**Comment by wouterj** [comment]
Yes, I'm working on it while also fixing https://github.com/weaverryan/docs-builder/issues/38 . Unfortunately, lists is implemented completely differently from definition lists, so I first have to investigate if we can safely rewrite it to be the same.

**Comment by wouterj** [comment]
https://github.com/doctrine/rst-parser/pull/143 is now merged, this should be fixed now.

**Comment by fabpot** [comment]
It works great! Thank you.

**Comment by wouterj** [comment]
Oh, that's interesting. I'll check somewhere today with the rst-parser test suite

**Comment by wouterj** [comment]
@javiereguiluz I cannot reproduce locally using Sphinx 1.8.5 (which should be the version used on symfony.com):

```
$ git clone https://github.com/doctrine/rst-parser
$ ./tests/sphinx list
$ grep -A6 'sub items' tests/Functional/_sphinx/list.html
<li><p class="first">This is an item with sub items</p>
<ul class="simple">
<li>A valid</li>
<li>subitem</li>
<li>list</li>
</ul>
</li>
```

**Comment by javiereguiluz** [comment]
OK, let's close this because Wouter explained the tech reasons behind this ... and we've tweaked the design a bit to neutralize this change. Thanks!
