### ISSUE TITLE
CI check - check external link for validity

### ISSUE THREAD

**Issue by nikophil** [symfony-tools/docs-builder#8]
see https://github.com/weaverryan/symfony-docs/issues/17

**Comment by nikophil** [comment]
i've opened a PR on the parser, to fix the behavior on the raw url automatically being translated to a `<a>`
https://github.com/doctrine/rst-parser/pull/82

**Comment by javiereguiluz** [comment]
I'm closing this one as "won't fix". It's not a bad idea of course ... but 90% of our links point to php.net, github.com or wikipedia.org, so those links will be always available.

For the rare links pointing to other hosts, let's rely on our readers that will quickly tell us if some links is wrong or broken in some way. Thanks!
