### ISSUE TITLE
Add support for placeholders in includes?

### ISSUE THREAD

**Issue by javiereguiluz** [symfony-tools/docs-builder#90]
In Symfony Docs we use includes with placeholders.

E.g. this file -> https://raw.githubusercontent.com/symfony/symfony-docs/5.x/reference/forms/types/choice.rst includes things like this:

```rst
compound
~~~~~~~~

**type**: ``boolean`` **default**: same value as ``expanded`` option

This option specifies if a form is compound. The value is by default
overridden by the value of the ``expanded`` option.

.. include:: /reference/forms/types/options/empty_data.rst.inc
    :end-before: DEFAULT_PLACEHOLDER
```

The included file is this one: https://github.com/symfony/symfony-docs/blob/5.x/reference/forms/types/options/empty_data.rst.inc which includes the `DEFAULT_PLACEHOLDER` string.

However, the new builder doesn't support it and it's displayed like this:

![image](https://user-images.githubusercontent.com/73419/113150568-8313ce00-9234-11eb-8b1c-6de2d2bb9c21.png)

Should we support this feature in this builder?

**Comment by stof** [comment]
I would say that the missing thing is support for the `:end-before:` setting of the include directive. `DEFAULT_PLACEHOLDER` does not look like a sphinx feature. It is the value that our doc uses when using the `:end-before:` feature.

**Comment by stof** [comment]
Also, the include directive is implemented in the upstream rst-parser (and is not an actual directive)

**Comment by javiereguiluz** [comment]
This is not easy to implement at all ... and we used it just in a couple of doc pages, so let's close as "won't fix". Thanks.
